[programs.devnet]
myepicproject = "9688YWvxPeaQfbjvugbHA6mpbETXFPqLassF4ms7JPVR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.devnet.solana.com"
url = "https://api.devnet.solana.com"
wallet = "/Users/hardworker1002/desktop/solana/my-keypair.json"

[scripts]
test = "node tests/myepicproject.js"
